stages:
  - rpm-package
  - local-test

rpm-package-rhel7:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

rpm-package-rhel8:
  stage: rpm-package
  script:
    - 'rpm-package.sh rhel8'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  except:
    - master
